"""schema inicial

Revision ID: 3540a09a1883
Revises: 
Create Date: 2026-10-02 23:09:55.927623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3540a09a1883'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imagem', sa.String(length=255), nullable=True),
    sa.Column('titulo', sa.String(length=80), nullable=False),
    sa.Column('texto_botao', sa.String(length=30), nullable=False),
    sa.Column('link', sa.String(length=255), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_banners'))
    )
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=60), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('imagem', sa.String(length=255), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categorias'))
    )
    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categorias_slug'), ['slug'], unique=True)

    op.create_table('cupons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=40), nullable=False),
    sa.Column('tipo', sa.String(length=12), nullable=False),
    sa.Column('valor', sa.Integer(), nullable=False),
    sa.Column('minimo', sa.Integer(), nullable=False),
    sa.Column('validade', sa.DateTime(timezone=True), nullable=True),
    sa.Column('limite_uso', sa.Integer(), nullable=True),
    sa.Column('usos', sa.Integer(), nullable=False),
    sa.Column('acumula_pix', sa.Boolean(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.CheckConstraint("tipo <> 'PERCENTUAL' OR valor <= 100", name=op.f('ck_cupons_percentual_ate_100')),
    sa.CheckConstraint('valor > 0', name=op.f('ck_cupons_valor_positivo')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cupons'))
    )
    with op.batch_alter_table('cupons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cupons_codigo'), ['codigo'], unique=True)

    op.create_table('pagamentos_simulados',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('referencia', sa.String(length=12), nullable=False),
    sa.Column('valor', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pagamentos_simulados'))
    )
    with op.batch_alter_table('pagamentos_simulados', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pagamentos_simulados_referencia'), ['referencia'], unique=False)

    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('papel', sa.String(length=10), nullable=False),
    sa.Column('google_sub', sa.String(length=64), nullable=True),
    sa.Column('versao_sessao', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usuarios')),
    sa.UniqueConstraint('google_sub', name=op.f('uq_usuarios_google_sub'))
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_email'), ['email'], unique=True)

    op.create_table('enderecos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('apelido', sa.String(length=40), nullable=False),
    sa.Column('cep', sa.String(length=8), nullable=False),
    sa.Column('rua', sa.String(length=160), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('complemento', sa.String(length=80), nullable=True),
    sa.Column('bairro', sa.String(length=80), nullable=False),
    sa.Column('cidade', sa.String(length=80), nullable=False),
    sa.Column('uf', sa.String(length=2), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('fk_enderecos_usuario_id_usuarios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_enderecos'))
    )
    with op.batch_alter_table('enderecos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_enderecos_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('pedidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=12), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('endereco', sa.JSON(), nullable=True),
    sa.Column('tipo_frete', sa.String(length=10), nullable=False),
    sa.Column('prazo_frete', sa.String(length=60), nullable=False),
    sa.Column('valor_frete', sa.Integer(), nullable=False),
    sa.Column('subtotal', sa.Integer(), nullable=False),
    sa.Column('desconto_cupom', sa.Integer(), nullable=False),
    sa.Column('desconto_pix', sa.Integer(), nullable=False),
    sa.Column('desconto', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('cupom_codigo', sa.String(length=40), nullable=True),
    sa.Column('forma_pagamento', sa.String(length=10), nullable=False),
    sa.Column('id_pagamento_gateway', sa.String(length=64), nullable=True),
    sa.Column('pix_copia_cola', sa.Text(), nullable=True),
    sa.Column('pix_qr_imagem', sa.Text(), nullable=True),
    sa.Column('expira_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pago_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rastreio', sa.String(length=60), nullable=True),
    sa.Column('motivo_cancelamento', sa.String(length=200), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('estoque_devolvido', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('fk_pedidos_usuario_id_usuarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pedidos'))
    )
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pedidos_id_pagamento_gateway'), ['id_pagamento_gateway'], unique=False)
        batch_op.create_index(batch_op.f('ix_pedidos_numero'), ['numero'], unique=True)
        batch_op.create_index(batch_op.f('ix_pedidos_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_pedidos_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('produtos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=140), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('composicao', sa.String(length=200), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('preco', sa.Integer(), nullable=False),
    sa.Column('preco_promocional', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('preco > 0', name=op.f('ck_produtos_preco_positivo')),
    sa.CheckConstraint('preco_promocional IS NULL OR preco_promocional > 0', name=op.f('ck_produtos_promocional_positivo')),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], name=op.f('fk_produtos_categoria_id_categorias')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_produtos'))
    )
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_produtos_categoria_id'), ['categoria_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_produtos_slug'), ['slug'], unique=True)

    op.create_table('sacolas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('token', sa.String(length=64), nullable=True),
    sa.Column('cupom_codigo', sa.String(length=40), nullable=True),
    sa.Column('cep_frete', sa.String(length=8), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('fk_sacolas_usuario_id_usuarios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sacolas')),
    sa.UniqueConstraint('token', name=op.f('uq_sacolas_token')),
    sa.UniqueConstraint('usuario_id', name=op.f('uq_sacolas_usuario_id'))
    )
    op.create_table('favoritos',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], name=op.f('fk_favoritos_produto_id_produtos'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('fk_favoritos_usuario_id_usuarios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('usuario_id', 'produto_id', name=op.f('pk_favoritos'))
    )
    op.create_table('imagens_produto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('alt', sa.String(length=200), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], name=op.f('fk_imagens_produto_produto_id_produtos'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_imagens_produto'))
    )
    with op.batch_alter_table('imagens_produto', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_imagens_produto_produto_id'), ['produto_id'], unique=False)

    op.create_table('variacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('cor', sa.String(length=40), nullable=False),
    sa.Column('cor_hex', sa.String(length=7), nullable=False),
    sa.Column('tamanho', sa.String(length=4), nullable=False),
    sa.Column('sku', sa.String(length=60), nullable=False),
    sa.Column('estoque', sa.Integer(), nullable=False),
    sa.CheckConstraint('estoque >= 0', name=op.f('ck_variacoes_estoque_nao_negativo')),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], name=op.f('fk_variacoes_produto_id_produtos'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_variacoes')),
    sa.UniqueConstraint('produto_id', 'cor', 'tamanho', name='uq_variacoes_produto_cor_tamanho'),
    sa.UniqueConstraint('sku', name=op.f('uq_variacoes_sku'))
    )
    with op.batch_alter_table('variacoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_variacoes_produto_id'), ['produto_id'], unique=False)

    op.create_table('itens_pedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('variacao_id', sa.Integer(), nullable=True),
    sa.Column('produto_nome', sa.String(length=120), nullable=False),
    sa.Column('produto_slug', sa.String(length=140), nullable=False),
    sa.Column('cor', sa.String(length=40), nullable=False),
    sa.Column('tamanho', sa.String(length=4), nullable=False),
    sa.Column('sku', sa.String(length=60), nullable=False),
    sa.Column('imagem_url', sa.String(length=255), nullable=True),
    sa.Column('preco_unitario', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], name=op.f('fk_itens_pedido_pedido_id_pedidos'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variacao_id'], ['variacoes.id'], name=op.f('fk_itens_pedido_variacao_id_variacoes'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_itens_pedido'))
    )
    with op.batch_alter_table('itens_pedido', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_itens_pedido_pedido_id'), ['pedido_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_itens_pedido_variacao_id'), ['variacao_id'], unique=False)

    op.create_table('itens_sacola',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sacola_id', sa.Integer(), nullable=False),
    sa.Column('variacao_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.CheckConstraint('quantidade > 0', name=op.f('ck_itens_sacola_quantidade_positiva')),
    sa.ForeignKeyConstraint(['sacola_id'], ['sacolas.id'], name=op.f('fk_itens_sacola_sacola_id_sacolas'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variacao_id'], ['variacoes.id'], name=op.f('fk_itens_sacola_variacao_id_variacoes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_itens_sacola')),
    sa.UniqueConstraint('sacola_id', 'variacao_id', name='uq_itens_sacola_sacola_variacao')
    )
    with op.batch_alter_table('itens_sacola', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_itens_sacola_sacola_id'), ['sacola_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('itens_sacola', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_itens_sacola_sacola_id'))

    op.drop_table('itens_sacola')
    with op.batch_alter_table('itens_pedido', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_itens_pedido_variacao_id'))
        batch_op.drop_index(batch_op.f('ix_itens_pedido_pedido_id'))

    op.drop_table('itens_pedido')
    with op.batch_alter_table('variacoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_variacoes_produto_id'))

    op.drop_table('variacoes')
    with op.batch_alter_table('imagens_produto', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_imagens_produto_produto_id'))

    op.drop_table('imagens_produto')
    op.drop_table('favoritos')
    op.drop_table('sacolas')
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_produtos_slug'))
        batch_op.drop_index(batch_op.f('ix_produtos_categoria_id'))

    op.drop_table('produtos')
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pedidos_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_pedidos_status'))
        batch_op.drop_index(batch_op.f('ix_pedidos_numero'))
        batch_op.drop_index(batch_op.f('ix_pedidos_id_pagamento_gateway'))

    op.drop_table('pedidos')
    with op.batch_alter_table('enderecos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_enderecos_usuario_id'))

    op.drop_table('enderecos')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_email'))

    op.drop_table('usuarios')
    with op.batch_alter_table('pagamentos_simulados', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pagamentos_simulados_referencia'))

    op.drop_table('pagamentos_simulados')
    with op.batch_alter_table('cupons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cupons_codigo'))

    op.drop_table('cupons')
    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categorias_slug'))

    op.drop_table('categorias')
    op.drop_table('banners')
    # ### end Alembic commands ###
